[package]
name = "qudit-tensor"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lints.rust]
unused = { level = "allow", priority = -1 }

[dependencies]
qudit-core = { path = "../qudit-core" }
qudit-expr = { path = "../qudit-expr" }
bit-set = "0.8.0"
faer = "0.23.2"
